server:
  listening_address: '0.0.0.0'
  listening_port: 50001

clients:
  hostname_based_ids: True

  image_size:
    width: 320
    height: 240

  frame_rate: 20

  parameters_below_threshold:
    gain: 2
    sample_time: 1

  parameters_above_threshold:
    gain: 0.1
    sample_time: 0.1

  activation_level_threshold: 15

dependencies:
  1:
    - 0.0
    - 0.5
    - 0.2
    - 0.0
    - 0.0
  2:
    - 0.5
    - 0.0
    - 0.5
    - 0.1
    - 0.0
  3:
    - 0.1
    - 0.5
    - 0.0
    - 0.5
    - 0.2
  4:
    - 0.0
    - 0.1
    - 0.5
    - 0.0
    - 0.5
  5:
    - 0.0
    - 0.0
    - 0.2
    - 0.5
    - 0.0
